project_id = "bakyhjddhqxxsvseygst"

[functions.generate-medical-report]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = true

[functions.initialize-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
