// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bakyhjddhqxxsvseygst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJha3loamRkaHF4eHN2c2V5Z3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDEzMjcsImV4cCI6MjA3NDI3NzMyN30.rhu5UaNYLs-5g_A3DjtA2qRxYsbY83dTNGj-p5SS2QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});