// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhrbmfpsjahwxgdylmar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocmJtZnBzamFod3hnZHlsbWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2NjAzMzcsImV4cCI6MjA5ODIzNjMzN30.nt5GhT9CaSo1hINZLEhJIkHiOCf704DPGmXRt2mrTyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'telivus-ai-app',
    },
  },
});

// Handle auth errors globally
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT' && !session) {
    // Clear any stale session data
    localStorage.removeItem('supabase.auth.token');
  }
});
